### AVR assembler executable Makefile for Posix

PROGRAMMER = -cusbtiny
#PROGRAMMER = -cstk500v1 -P/dev/tty.usbmodem34521

MCU    = attiny85

# clockdiv/8, 8mhz RC oscillator, 4ms startup
LFUSE	= 0x52
HFUSE	= 0xDF
EFUSE 	= 0xFF

include ../base-asm.mk