### AVR executable Makefile for Posix

PROGRAMMER = -cusbtiny
#PROGRAMMER = -cstk500v1 -P/dev/tty.usbmodem34521
#NO_CORELIB = true
#OPTIMIZE = 3

F_CPU 	= 8000000L
MCU	= attiny85

LIBS 	= -lTinyDebugSerial
INC	= -I ../lib/TinyDebugSerial

include ../base.mk